
@api = http://localhost:8000/admins


GET {{api}}

###
GET {{api}}/2


###
GET {{api}}/count


###
POST {{api}}
Content-Type: application/json

{
   
    "nombre": "Raul",
    "apellidos": "Obando",
    "documento": "4587805",
    "email": "raul@gmail.com",
    "telefono": "3205716188",
    "password": "123456"
  }

###

DELETE {{api}}/20


###

PUT {{api}}/20
Content-Type: application/json

{
   
    "nombre": "alba actualizado",
    "apellidos": "Riascos",
    "documento": "633534353",
    "email": "marina@gmail.com",
    "telefono": "3145716188",
    "password": "123456"
  } 